# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'NeuralStyleTransfer' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for NeuralStyleTransfer
  pod 'Toast-Swift', '~> 5.0.1'

end
